# Generated by Django 5.2.3 on 2025-06-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
